services:
    sio_test:
        user: app
        build:
            context: .
            args:
                USER_ID: ${USER_ID:-1000}
        ports:
            - "8337:8337"
        volumes:
            - .:/app:rw
        environment:
            - APP_ENV=dev

###> doctrine/doctrine-bundle ###
    database:
      image: mysql:${MYSQL_VERSION:-8.0}
      environment:
        MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
        MYSQL_USER: ${MYSQL_USER:-app}
        # You should definitely change the password in production
        MYSQL_PASSWORD: ${MYSQL_PASSWORD:-!ChangeMe!}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-!ChangeMe!}
        MYSQL_TCP_PORT: 3307
      volumes:
        - database_data:/var/lib/mysql:rw
        # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
        # - ./docker/db/data:/var/lib/mysql:rw
      ports:
        - "3307:3307"
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
